### ISSUE TITLE
Document the schema

### ISSUE THREAD

**Issue by waldoj** [opendata/Hunting-and-Fishing#49]
Create a GitHub Pages-hosted project to document the schema. Properly created JSON schemas should make it possible to build the core of the documentation automatically.

**Comment by waldoj** [comment]
I tried running matic. It just creates a directory with the schemas in it. I can't get it to generate documentation—most config options just produce this:

```
$ matic
/usr/local/lib/node_modules/matic/lib/build.js:18
    this.clipboard.files[fileName] = template(index.call(this, config));
                                     ^
TypeError: undefined is not a function
    at module.exports (/usr/local/lib/node_modules/matic/lib/build.js:18:38)
    at module.exports (/usr/local/lib/node_modules/matic/node_modules/rightclick/lib/tap.js:4:24)
    at /usr/local/lib/node_modules/matic/lib/matic.js:19:8
    at FSReqWrap.oncomplete (fs.js:99:15)
```
